"use client";

import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { WebGLFallback } from "./WebGLFallback";
import { useI18n } from "@/lib/i18n";
import { useTheme } from "@/components/theme/ThemeProvider";
import { ArrowRight, CheckCircle2, Home, Rotate3D, Wrench, X } from "lucide-react";

interface HeroScene3DProps { onSelectCategory?: (serviceId: string) => void; onBookClick?: (serviceId?: string) => void; }
type ViewMode = "outside" | "inside";

type Target = { en:string; hi:string; emoji:string; service:string; problem:string; problemHi:string };
const targetInfo: Record<string,Target> = {
  tap:{en:"Tap / Pipe",hi:"नल / पाइप",emoji:"🚰",service:"plumber",problem:"Water leaking or tap not working?",problemHi:"पानी लीक हो रहा है या नल काम नहीं कर रहा?"},
  sink:{en:"Kitchen Sink",hi:"रसोई सिंक",emoji:"🚰",service:"plumber",problem:"Sink blocked or leaking?",problemHi:"सिंक जाम या लीक हो रहा है?"},
  fridge:{en:"Fridge",hi:"फ्रिज",emoji:"🧊",service:"electrician",problem:"Fridge not cooling?",problemHi:"फ्रिज ठंडा नहीं कर रहा?"},
  kitchen:{en:"Kitchen",hi:"रसोई",emoji:"🍳",service:"electrician",problem:"Kitchen appliance or wiring problem?",problemHi:"रसोई के सामान या बिजली में दिक्कत?"},
  toilet:{en:"Toilet",hi:"टॉयलेट",emoji:"🚽",service:"plumber",problem:"Flush or toilet problem?",problemHi:"फ्लश या टॉयलेट में दिक्कत?"},
  shower:{en:"Shower",hi:"शॉवर",emoji:"🚿",service:"plumber",problem:"Shower or water pressure problem?",problemHi:"शॉवर या पानी के प्रेशर में दिक्कत?"},
  washing:{en:"Washing Machine",hi:"वॉशिंग मशीन",emoji:"🧺",service:"appliance-repair",problem:"Washing machine not working?",problemHi:"वॉशिंग मशीन काम नहीं कर रही?"},
  bed:{en:"Bed / Furniture",hi:"बेड / फर्नीचर",emoji:"🛏️",service:"carpenter",problem:"Furniture, bed or door needs fixing?",problemHi:"फर्नीचर, बेड या दरवाजा ठीक करवाना है?"},
  electrician:{en:"Fan / Switch",hi:"पंखा / स्विच",emoji:"💡",service:"electrician",problem:"Fan, switch or wiring problem?",problemHi:"पंखा, स्विच या वायरिंग में दिक्कत?"},
  tv:{en:"TV / Wall",hi:"टीवी / दीवार",emoji:"📺",service:"electrician",problem:"TV, socket or wall mounting issue?",problemHi:"टीवी, सॉकेट या वॉल माउंटिंग में दिक्कत?"},
  "ac-repair":{en:"AC",hi:"एसी",emoji:"❄️",service:"ac-repair",problem:"AC not cooling or making noise?",problemHi:"एसी ठंडा नहीं कर रहा या आवाज़ कर रहा?"},
  door:{en:"Door / Window",hi:"दरवाजा / खिड़की",emoji:"🚪",service:"carpenter",problem:"Door, lock or window needs repair?",problemHi:"दरवाजा, लॉक या खिड़की ठीक करवानी है?"},
  mechanic:{en:"Car / Bike",hi:"गाड़ी / बाइक",emoji:"🔧",service:"mechanic",problem:"Vehicle not starting or needs service?",problemHi:"गाड़ी स्टार्ट नहीं हो रही या सर्विस चाहिए?"},
  tractor:{en:"Tractor / Khet",hi:"ट्रैक्टर / खेत",emoji:"🚜",service:"mechanic",problem:"Tractor or farm equipment problem?",problemHi:"ट्रैक्टर या खेती के सामान में दिक्कत?"},
  tank:{en:"Water Tank",hi:"पानी की टंकी",emoji:"💧",service:"plumber",problem:"Tank, pipe or water pressure problem?",problemHi:"टंकी, पाइप या पानी के प्रेशर में दिक्कत?"},
  garden:{en:"Garden",hi:"बगीचा",emoji:"🌳",service:"gardener",problem:"Garden maintenance needed?",problemHi:"बगीचे की देखभाल करवानी है?"},
};

export function HeroScene3D({onSelectCategory,onBookClick}:HeroScene3DProps){
 const mountRef=useRef<HTMLDivElement>(null); const [webglSupported,setWebglSupported]=useState(true); const [activeTarget,setActiveTarget]=useState("tap"); const [viewMode,setViewMode]=useState<ViewMode>("outside"); const [selectedTarget,setSelectedTarget]=useState<string|null>(null); const [hoveredTarget,setHoveredTarget]=useState<string|null>(null); const [room,setRoom]=useState("all"); const {lang}=useI18n(); const {theme}=useTheme(); const isDark=theme==="dark";
 useEffect(()=>{
  const c=document.createElement("canvas"); if(!(c.getContext("webgl")||c.getContext("experimental-webgl"))){setWebglSupported(false);return;} const container=mountRef.current;if(!container)return;
  const w=container.clientWidth,h=container.clientHeight||620,scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,w/h,.1,100); const outside=new THREE.Vector3(8.8,7.2,11.5),inside=new THREE.Vector3(0,3.2,9.2); camera.position.copy(viewMode==="inside"?inside:outside);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:"high-performance"}); renderer.setSize(w,h);renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=isDark?1.15:1.25;container.appendChild(renderer.domElement);
  scene.add(new THREE.AmbientLight(isDark?0x7890b8:0xfff4e8,isDark?1.9:2.4)); const sun=new THREE.DirectionalLight(isDark?0x8fb8ff:0xffe1bc,isDark?1.5:2.5);sun.position.set(7,13,8);sun.castShadow=true;scene.add(sun);const warm=new THREE.PointLight(0xffa13c,isDark?3.2:1.8,10);warm.position.set(0,2.8,2.5);scene.add(warm);
  const property=new THREE.Group();scene.add(property); const targets:{mesh:THREE.Object3D,id:string}[]=[]; const mat=(color:number,r=.7,m=0)=>new THREE.MeshStandardMaterial({color,roughness:r,metalness:m}); const wall=mat(isDark?0x334155:0xf5f1e8),floor=mat(isDark?0x1e293b:0xd8c5a6),wood=mat(0x9a4d1d,.65),green=mat(0x15803d,.9),dark=mat(0x1e293b,.35,.2),white=mat(0xf8fafc,.3),metal=mat(0x94a3b8,.3,.7),blue=mat(0x2563eb,.3,.15);
  const box=(sx:number,sy:number,sz:number,ma:THREE.Material,x:number,y:number,z:number,group=property)=>{const q=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),ma);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;group.add(q);return q}; const target=(q:THREE.Object3D,id:string)=>{q.userData.target=id;targets.push({mesh:q,id});return q};
  const base=box(15,.35,11,mat(isDark?0x0f172a:0xc8b89a),0,-.2,0);base.receiveShadow=true;
  box(4.6,.12,3.4,mat(isDark?0x14532d:0x86b85b),-5,.03,1.7);box(4,.12,4.2,mat(isDark?0x365314:0x84a83e),5.1,.03,-2.6); for(let r=-1.4;r<=1.4;r+=.7)for(let cc=-1.5;cc<=1.5;cc+=.65)box(.08,.28,.08,green,5.1+cc,.23,-2.6+r);
  const tree=(x:number,z:number,s=1)=>{box(.18*s,.9*s,.18*s,wood,x,.45*s,z);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.55*s,1),green);crown.position.set(x,1.25*s,z);crown.castShadow=true;property.add(crown)};tree(-6.1,0,1.25);tree(-4.7,3,.75);tree(6.4,1.6,.95);
  const house=new THREE.Group();house.position.z=-.6;property.add(house); const add=(q:THREE.Mesh)=>{q.castShadow=true;q.receiveShadow=true;house.add(q);return q}; add(new THREE.Mesh(new THREE.BoxGeometry(7,.18,5),floor)).position.set(0,.1,0);add(new THREE.Mesh(new THREE.BoxGeometry(7,.18,5),floor)).position.set(0,3.15,0);
  const parts=[[.12,2.9,4.8,-1.05,1.55,0],[3.2,2.9,.12,1.55,1.55,0],[.12,2.9,4.8,0,1.55,-.45]];parts.forEach(p=>{const q=add(new THREE.Mesh(new THREE.BoxGeometry(p[0],p[1],p[2]),wall));q.position.set(p[3],p[4],p[5])}); add(new THREE.Mesh(new THREE.BoxGeometry(1.5,2.9,.14),wall)).position.set(-2.7,1.55,2.45);add(new THREE.Mesh(new THREE.BoxGeometry(1.6,2.9,.14),wall)).position.set(2.7,1.55,2.45);
  const roof=add(new THREE.Mesh(new THREE.ConeGeometry(5,1.45,4),mat(0xd97706,.58)));roof.position.set(0,6.25,-.1);roof.rotation.y=Math.PI/4; const tankMesh=target(add(new THREE.Mesh(new THREE.CylinderGeometry(.75,.75,1.25,16),metal)),"tank");tankMesh.position.set(-1.6,7.05,-.3);add(new THREE.Mesh(new THREE.BoxGeometry(1.8,.08,1),mat(0x172554,.2,.5))).position.set(1.3,6.75,-.4);
  box(1,1.9,.14,wood,0,1.05,2.55); [-2.2,2.2].forEach(x=>box(1,1,.08,new THREE.MeshStandardMaterial({color:0x60a5fa,transparent:true,opacity:.55}),x,1.55,2.55,false as any));
  // Living room: sofa, TV, table, fan, switch, door/window
  target(box(2.7,.7,1,wood,-2.15,.65,-1.45),"bed"); box(2.3,.38,.9,mat(0x475569),-2.15,1.05,-1.45); target(box(.45,.9,.45,mat(0x64748b),-.7,.55,-.35),"tv"); target(box(1.2,.06,.65,wood,-.7,1.02,-.35),"tv"); target(box(.16,.16,.08,metal,-1.05,2.2,2.38),"electrician");
  // Kitchen: counter, sink, fridge, stove, cabinets
  target(box(2.5,.8,.7,wood,1.45,.55,-1.75),"kitchen"); target(box(.75,.08,.5,metal,1.1,.98,-1.75),"sink"); target(box(.12,.55,.12,metal,1.1,1.2,-1.75),"tap"); target(box(.7,1.55,.65,white,2.55,.8,-1.75),"fridge"); target(box(.75,.12,.55,dark,1.95,.99,-1.75),"kitchen"); box(2.1,.35,.08,wood,1.45,1.75,-1.75);
  // Bedroom: bed, side tables, wardrobe, window
  target(box(1.7,.35,2.2,white,-2.05,3.45,-1.2),"bed"); box(1.2,.1,.55,wood,-2.05,3.85,-2.15); target(box(.8,1.7,.55,wood,-.65,4.05,-1.7),"door"); box(.35,.5,.35,metal,-3.05,3.75,-2.2);
  // Bathroom: toilet, shower, sink, mirror, washing machine
  target(new THREE.Mesh(new THREE.CylinderGeometry(.32,.38,.5,12),white),"toilet").position.set(2.25,.4,1.45); const toilet=targets[targets.length-1].mesh;house.add(toilet);
  target(box(.8,.08,.8,blue,1.45,.25,1.35),"shower"); target(box(.65,.75,.5,white,2.55,.5,1.25),"washing"); target(box(.75,.45,.45,white,1.35,.45,1.95),"sink"); target(box(.65,.8,.04,mat(0xcbd5e1,.15,.2),1.35,1.2,1.7),"shower");
  // Upper room electrical + AC
  const fan=target(new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,.06,12),metal),"electrician");fan.position.set(-1.8,5.75,.4);house.add(fan);target(box(.85,.45,.28,white,2.15,5,2.35),"ac-repair"); target(box(.18,.22,.08,metal,2.1,4.2,2.38),"electrician");
  // Outside services
  target(box(.12,.55,.12,metal,-4,.45,1),"tap");target(box(.65,.5,.5,mat(0x0f766e,.4,.3),-5.3,.35,3.1),"tap"); target(box(1.8,.55,2.8,blue,4.5,.7,2),"mechanic"); target(box(.5,.75,1.3,mat(0xdc2626,.4),6.5,.55,2.7),"mechanic"); target(box(1.2,.65,1.7,mat(0x16a34a,.55),6.1,.55,-4.1),"tractor"); target(new THREE.Mesh(new THREE.SphereGeometry(.35,16,16),green),"garden").position.set(-5,.7,1.7);
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let dragging=false,lastX=0,rotation=0; const pick=(e:MouseEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);for(const hit of ray.intersectObjects(property.children,true)){let n:THREE.Object3D|null=hit.object;while(n&&!n.userData.target)n=n.parent;if(n?.userData.target&&targetInfo[n.userData.target]){setActiveTarget(n.userData.target);setSelectedTarget(n.userData.target);return;}}};
  const hover=(e:MouseEvent)=>{if(dragging){rotation+=(e.clientX-lastX)*.006;lastX=e.clientX;return}const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);let id:string|null=null;for(const hit of ray.intersectObjects(property.children,true)){let n:THREE.Object3D|null=hit.object;while(n&&!n.userData.target)n=n.parent;if(n?.userData.target){id=n.userData.target;break}}setHoveredTarget(id)};
  const down=(e:PointerEvent)=>{dragging=true;lastX=e.clientX};const up=()=>{dragging=false};const canvas=renderer.domElement;canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointerleave",up);canvas.addEventListener("mousemove",hover);canvas.addEventListener("click",pick);const resize=()=>{const W=container.clientWidth,H=container.clientHeight||620;camera.aspect=W/H;camera.updateProjectionMatrix();renderer.setSize(W,H)};window.addEventListener("resize",resize);
  const clock=new THREE.Clock();let raf=0;const animate=()=>{raf=requestAnimationFrame(animate);const t=clock.getElapsedTime();if(!dragging)rotation+=.0006;property.rotation.y+=(rotation-property.rotation.y)*.055;camera.position.lerp(viewMode==="inside"?inside:outside,.045);camera.lookAt(viewMode==="inside"?new THREE.Vector3(0,3,0):new THREE.Vector3(0,2,0));warm.intensity=(isDark?3:1.7)+Math.sin(t*2)*.18;renderer.render(scene,camera)};animate();
  return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize);canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointerleave",up);canvas.removeEventListener("mousemove",hover);canvas.removeEventListener("click",pick);renderer.dispose();if(container.contains(canvas))container.removeChild(canvas)};
 },[isDark,viewMode]);
 if(!webglSupported)return <WebGLFallback/>; const active=targetInfo[activeTarget]||targetInfo.tap;
 const rooms=[['all','🏠',lang==='en'?'Whole Property':'पूरा घर'],['living','🛋️',lang==='en'?'Living Room':'बैठक'],['kitchen','🍳',lang==='en'?'Kitchen':'रसोई'],['bedroom','🛏️',lang==='en'?'Bedroom':'कमरा'],['bathroom','🚿',lang==='en'?'Bathroom':'बाथरूम'],['outside','🌳',lang==='en'?'Garden & Farm':'बगीचा और खेत']];
 return <div className="relative h-[520px] md:h-[640px] w-full overflow-hidden rounded-[2rem] border border-slate-200/70 bg-gradient-to-b from-sky-50 via-white to-emerald-50 dark:border-slate-800 dark:from-[#08111f] dark:via-[#0b1325] dark:to-[#0a1715] select-none"><div ref={mountRef} className="absolute inset-0 cursor-grab active:cursor-grabbing"/>
  <div className="absolute left-4 top-4 z-30 flex gap-2"><button onClick={()=>setViewMode("outside")} className={`flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-black shadow-lg backdrop-blur ${viewMode==='outside'?'bg-brand-orange text-white':'bg-white/90 text-slate-800 dark:bg-slate-900/90 dark:text-white'}`}><Home className="h-3.5 w-3.5"/>{lang==='en'?'Outside':'बाहर'}</button><button onClick={()=>setViewMode("inside")} className={`flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-black shadow-lg backdrop-blur ${viewMode==='inside'?'bg-brand-orange text-white':'bg-white/90 text-slate-800 dark:bg-slate-900/90 dark:text-white'}`}><Rotate3D className="h-3.5 w-3.5"/>{lang==='en'?'Enter Home':'घर के अंदर'}</button></div>
  <div className="absolute left-4 top-16 z-30 max-w-[calc(100%-2rem)] overflow-x-auto"><div className="flex gap-2 pb-1">{rooms.map(([id,emoji,label])=><button key={id} onClick={()=>setRoom(id)} className={`whitespace-nowrap rounded-full px-3 py-2 text-[11px] font-black shadow-lg backdrop-blur ${room===id?'bg-brand-orange text-white':'bg-white/90 text-slate-800 dark:bg-slate-900/90 dark:text-white'}`}>{emoji} {label}</button>)}</div></div>
  <div className="absolute right-4 top-4 z-30 rounded-xl bg-slate-950/65 px-3 py-2 text-[11px] font-bold text-white shadow-lg backdrop-blur">{viewMode==='inside'?(lang==='en'?'Inside • click an item to repair':'अंदर • किसी चीज़ पर क्लिक करके ठीक करवाएं'):(lang==='en'?'Explore your home':'अपना घर देखें')}</div>
  {hoveredTarget&&<div className="absolute left-1/2 top-28 z-30 -translate-x-1/2 rounded-full bg-white/95 px-4 py-2 text-xs font-black text-slate-800 shadow-xl dark:bg-slate-900/95 dark:text-white">{targetInfo[hoveredTarget]?.emoji} {lang==='en'?targetInfo[hoveredTarget]?.en:targetInfo[hoveredTarget]?.hi}</div>}
  {selectedTarget&&<div className="absolute left-1/2 top-1/2 z-40 w-[min(92%,380px)] -translate-x-1/2 -translate-y-1/2 rounded-3xl border border-white/20 bg-slate-950/90 p-5 text-white shadow-2xl backdrop-blur-xl"><button onClick={()=>setSelectedTarget(null)} className="absolute right-3 top-3 rounded-full p-1 text-slate-400 hover:bg-white/10 hover:text-white"><X className="h-4 w-4"/></button><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-orange/20 text-3xl">{targetInfo[selectedTarget].emoji}</div><div><div className="text-lg font-black">{lang==='en'?targetInfo[selectedTarget].en:targetInfo[selectedTarget].hi}</div><div className="text-xs text-emerald-300">{lang==='en'?targetInfo[selectedTarget].problem:targetInfo[selectedTarget].problemHi}</div></div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{onSelectCategory?.(targetInfo[selectedTarget].service);setSelectedTarget(null)}} className="rounded-xl bg-brand-orange px-3 py-3 text-sm font-black">{lang==='en'?'Find Kaamigar':'कामिगार ढूंढें'}</button><button onClick={()=>{onBookClick?.(targetInfo[selectedTarget].service);setSelectedTarget(null)}} className="rounded-xl border border-white/15 bg-white/10 px-3 py-3 text-sm font-black">{lang==='en'?'Book now':'अभी बुक करें'}</button></div></div>}
  <div className="absolute bottom-4 left-4 right-4 z-30 flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-slate-950/80 p-3 text-white shadow-2xl backdrop-blur-xl md:left-6 md:right-6"><div className="flex min-w-0 items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-brand-orange/20 text-xl">{active.emoji}</div><div className="min-w-0"><div className="truncate text-sm font-black">{lang==='en'?active.en:active.hi}</div><div className="mt-0.5 flex items-center gap-1 text-[11px] font-semibold text-emerald-300"><CheckCircle2 className="h-3 w-3"/>{lang==='en'?'Click an object to find the right worker':'चीज़ पर क्लिक करें — सही कामिगार ढूंढें'}</div></div></div><button onClick={()=>onBookClick?.(active.service)} className="flex shrink-0 items-center gap-1.5 rounded-xl bg-brand-orange px-4 py-2.5 text-xs font-black text-white shadow-lg hover:bg-orange-600"><Wrench className="h-3.5 w-3.5"/>{lang==='en'?'Repair / Book':'मरम्मत / बुक करें'}<ArrowRight className="h-3.5 w-3.5"/></button></div>
  <div className="absolute bottom-[88px] right-4 z-20 hidden rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-bold text-slate-700 shadow-lg backdrop-blur sm:flex dark:bg-slate-900/80 dark:text-slate-200">↔ {lang==='en'?'Drag to explore • click objects':'घुमाकर देखें • चीज़ों पर क्लिक करें'}</div>
 </div>;
}